/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kjs_skywalk_communicationlibrary_NativeCall */

#ifndef _Included_com_kjs_skywalk_communicationlibrary_NativeCall
#define _Included_com_kjs_skywalk_communicationlibrary_NativeCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kjs_skywalk_communicationlibrary_NativeCall
 * Method:    GeneratePassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kjs_skywalk_communicationlibrary_NativeCall_GeneratePassword
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     com_kjs_skywalk_communicationlibrary_NativeCall
 * Method:    GenerateReloginSession
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kjs_skywalk_communicationlibrary_NativeCall_GenerateReloginSession
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
